### ISSUE TITLE
Verify in TearDown method hides source of the problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#124]
```
In order to better structure my unit tests I have been taking advantage of
the SetUp and TearDown methods provided by nUnit.

In the process of this I have begun doing my Moq verifications in the
teardown method.

However, I have found that the result is that the location of the problem
is hidden from me. When a problem is found, the Unit Test Session output
says that expectations were not met and provides me with a link to the
location in the teardown method which is very unhelpful as it is not the
source of the problem.

Is it possible to have the MockVerificationException return a link not only
of the place where the verification failed but also of the place where the
particular expectation was created? As it currently stands, when there are
more than a handful of tests it becomes increasingly difficult to instantly
locate the source of the problem. 

I've created a test solution in VS2008 that demonstrates the issue.

What steps will reproduce the problem?
1. Create a mock with expectations
2. Set the class up so that one of the expectations deliberately fails
3. Set the verification to take place in the teardown method
4. Run the test

The result I would expect to see is:
Moq.MockVerificationException: The following expectations were not met:
IClass2 p => p.MyMethod2() (TestMyMethod()in Class1Tests.cs: line 29)

at Moq.Mock.VerifyAll(Interceptor interceptor)
at Moq.Mock`1.VerifyAll()
at ClassLibrary1.Class1Tests.TearDown() in Class1Tests.cs: line 22 

The result I see is:
Moq.MockVerificationException: The following expectations were not met:
IClass2 p => p.MyMethod2()

at Moq.Mock.VerifyAll(Interceptor interceptor)
at Moq.Mock`1.VerifyAll()
at ClassLibrary1.Class1Tests.TearDown() in Class1Tests.cs: line 22 


What version of the product are you using? 2.6.1014.1 On what operating
system? Windows XP


Please provide any additional information below.

You should find the solution attached as a zip file. Let me know if there
is a problem with it.

```

Original issue reported on code.google.com by `joshuajr...@gmail.com` on 22 Jan 2009 at 7:11

Attachments:
- [ClassLibrary1.zip](https://storage.googleapis.com/google-code-attachments/moq/issue-124/comment-0/ClassLibrary1.zip)

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 3 Feb 2009 at 3:44
- Changed state: **Fixed**
- Added labels: **Milestone-Release3.0**, **Type-Enhancement**, **Usability**
- Removed labels: **Type-Defect**
