### ISSUE TITLE
MockVerificationException displaying incorrect method signature

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#134]
```
When I accidentally request an expectation that isn't met, Moq will display
the wrong expectation in the results.

//Given the following interface....
using System.Net.Mail;

namespace MyNameSpace
{

    public interface IEmailService
    {

        void SendEmail(string mailServer, string from, string toRecipient,
string ccRecipient, string bccRecipient, string subject, string body,
params Attachment[] attachments);
    }
}

//Steps to reproduce
Mock<IEmailService> emailMock = new Mock<IEmailService>();

emailMock.Expect(p => p.SendEmail(It.IsAny<string>(), It.IsAny<string>(),
It.IsAny<string>(), It.IsAny<string>(),
                 It.IsAny<string>(), It.IsAny<string>(),
It.IsAny<string>(), It.IsAny<Attachment>()));

sut.Send(/*snip*/); //sut that exercises the functionality we want and uses
the email service to send something
emailMock.VerifyAll();

Result:
Moq.MockVerificationException: The following expectations were not met:
IEmailService p => p.SendEmail(IsAny<String>(), IsAny<String>(),
IsAny<String>(), IsAny<String>(), IsAny<String>(), IsAny<String>(),
IsAny<String>(), new [] {IsAny<String>()})

at Moq.Mock.VerifyAll(Interceptor interceptor)
at Moq.Mock`1.VerifyAll()

I would expect that it wouldn't display new [] {IsAny<String>()} when the
type it is actually looking for is IsAny<Attachment>()

I am using Moq 2.6.1014.1 on WinXp
```

Original issue reported on code.google.com by `joshuajr...@gmail.com` on 11 Feb 2009 at 11:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 14 Feb 2009 at 3:55

**Comment by GoogleCodeExporter** [comment]
```
It was a problem in Expression.ToStringFixed extension method
```

Original comment by `marian...@gmail.com` on 17 Feb 2009 at 10:50
- Changed state: **Fixed**
