### ISSUE TITLE
Using It.Is<> results in NullReferenceException inside Moq implementation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#16]
```
Hi, 

I'm usng It.Is<> argument placeholder to verify that invokation 
parameters match the expected ones. It may look like: 


var foo = new Mock<IFoo>(); 


foo.Expect((f) => f.Foo(It.Is<int>((arg) => arg == 6))); 
foo.Object.Foo(6); 


The Problem is that predicate can be quite complex and thus in-lining 
it within Is() creates quite ugly and unreadable test code. In 
addition, the predicate may be reused in multiple places in the test. 
I wanted to factor out my predicate, so I refactored to this: 


Predicate<int> isSix = (arg) => arg == 6; 
foo.Expect((f) => f.Callback(It.Is(isSix))); 
foo.Object.Callback(6); 


This will not compile, since I realized Is() expects 
Expression<Predicate>, not Predicate itself. My first question is why 
it expects an Expression, not simply Predicate? I believe there is a 
good reason, I just can't get to it myself. 


So I continued with refactoring and now it looks like: 
Expression<Predicate<int>> isSix = (arg) => arg == 6; 
foo.Expect((f) => f.Foo(It.Is(isSix))); 
foo.Object.Foo(6); 


This compiles and seems to fit the bill. But now it throws inside Moq 
with NullReferenceException, which I believe may be a bug. Please take 
a look. 


Thanks a lot! 
-Eugene 

```

Original issue reported on code.google.com by `eugene.p...@gmail.com` on 13 Mar 2008 at 1:51

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I've been tried, but i had the following exception:

System.TypeLoadException was unhandled
  Message="Type 'IFooProxy6c57432bd8754c98bff8401ca1b1aaa5' from assembly
'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=null' is
attempting to implement an inaccessible interface."
  Source="mscorlib"
  TypeName="IFooProxy6c57432bd8754c98bff8401ca1b1aaa5"
  StackTrace:
       at System.Reflection.Emit.TypeBuilder._TermCreateClass(Int32 handle, Module
module)
       at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
       at System.Reflection.Emit.TypeBuilder.CreateType()
       at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType() in
C:\Stuff\Mocks\Castle-net-2.0-release-2007-9-20\castle-sourcecode\Tools\Castle.D
ynamicProxy2\Castle.DynamicProxy\Generators\Emitters\AbstractTypeEmitter.cs:line
262
       at
Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCode(Ty
pe
proxyTargetType, Type[] interfaces, ProxyGenerationOptions options) in
C:\Stuff\Mocks\Castle-net-2.0-release-2007-9-20\castle-sourcecode\Tools\Castle.D
ynamicProxy2\Castle.DynamicProxy\Generators\InterfaceProxyWithTargetGenerator.cs
:line
321
       at
Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarget(Ty
pe
theInterface, Type[] interfaces, ProxyGenerationOptions options) in
C:\Stuff\Mocks\Castle-net-2.0-release-2007-9-20\castle-sourcecode\Tools\Castle.D
ynamicProxy2\Castle.DynamicProxy\DefaultProxyBuilder.cs:line
66
       at
Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyTypeWithoutTarget(Type
theInterface, Type[] interfaces, ProxyGenerationOptions options) in
C:\Stuff\Mocks\Castle-net-2.0-release-2007-9-20\castle-sourcecode\Tools\Castle.D
ynamicProxy2\Castle.DynamicProxy\ProxyGenerator.cs:line
373
       at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type
theInterface, Type[] interfaces, ProxyGenerationOptions options, IInterceptor[]
interceptors) in
C:\Stuff\Mocks\Castle-net-2.0-release-2007-9-20\castle-sourcecode\Tools\Castle.D
ynamicProxy2\Castle.DynamicProxy\ProxyGenerator.cs:line
242
       at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type
theInterface, Type[] interfaces, IInterceptor[] interceptors) in
C:\Stuff\Mocks\Castle-net-2.0-release-2007-9-20\castle-sourcecode\Tools\Castle.D
ynamicProxy2\Castle.DynamicProxy\ProxyGenerator.cs:line
219
       at Moq.Mock`1..ctor(MockBehavior behavior, Object[] args) in
C:\projectos\moq\Source\Mock.cs:line 118
       at Moq.Mock`1..ctor(MockBehavior behavior) in
C:\projectos\moq\Source\Mock.cs:line 180
       at Moq.Mock`1..ctor() in C:\projectos\moq\Source\Mock.cs:line 172
       at ConsoleApplication1.Program.Main(String[] args) in
C:\projectos\moq\ConsoleApplication1\Program.cs:line 30
       at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext,
ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

I hope this help in anyway!

Best Regards,
Orlando Agostinho
Lisbon/Portugal

```

Original comment by `orlando....@gmail.com` on 15 Mar 2008 at 7:56

**Comment by GoogleCodeExporter** [comment]
```
1 - The function passed to It.Is must be an expression because the entire 
Expect()
receives an expression. That's how we can infer which methods and with which
arguments you want the expectation to match. It's annoying for It.Is with long
functions, but we're working to make extensibility of It.IsXXX substancially 
easier,
so you can plug your own stuff in there.

2 - weird... on the surface it looks as if you're trying to mock a non-public 
interface?
```

Original comment by `kzu.net` on 19 Mar 2008 at 5:01

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 26 Mar 2008 at 8:18
- Added labels: **Milestone-Release2.5**, **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
We decided to resolve this as "by design" as we're planning a different 
approach for
reusing the predicates.

We might reopen this issue if there's enough demand for expression-kind reuse 
as you
wrote, but I doubt it will be too popular ;)
```

Original comment by `kzu.net` on 2 Apr 2008 at 4:44
- Changed state: **WontFix**
