### ISSUE TITLE
Why can't I use the "Protected" extensions to test non-protected members?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#163]
```
What steps will reproduce the problem?
1. Create a Mock of an object that has a public property.  Example:

public interface IFoo {
      string Bar { get; }
}

2. Set up an expectation using the ProtectedExtensions 

[Test]
public void TestMethod() {
    Mock<IFoo> fooMock = new Mock<IFoo>;
    Moq.Protected.ProtectedExtension
        .Protected(fooMock).Expect("Bar", null);
    fooMock.Object.Bar;
    fooMock.VerifyAll();
}

I would expect Moq to go ahead an verify my expectation regardless of
whether or not the property is protected.  I want to have the ability to
test that all properties of an interface are called by a method.  I can use
reflection to get a reference to all properties exposed by the interface
and the I want to set an expectation on my mock that all properties are
called.  But I cannot do this because Moq gives the following error:

TestCase 'foo_bar_is_called'
not executed: System.ArgumentException : To set expectations for public
property IFoo.Bar, use the typed overloads, such as:
mock.Expect(x => x.Bar).Returns(value);
mock.ExpectGet(x => x.Bar).Returns(value); //equivalent to previous one
mock.ExpectSet(x => x.Bar).Callback(callbackDelegate);
    at Moq.Protected.ProtectedMock`1.VerifyProperty(PropertyInfo property)
    at Moq.Protected.ProtectedMock`1.Expect(String voidMethodName, Object[] args)

```

Original issue reported on code.google.com by `jeffdool...@gmail.com` on 9 Apr 2009 at 12:26

**Comment by GoogleCodeExporter** [comment]
```
This is by design as we don't want people using strings to refer to members 
unless
it's absolutely necessary (i.e. protected members).

Maybe this should be a "Moq.Unsafe" namespace and we could allow anything?
```

Original comment by `kzu.net` on 10 Apr 2009 at 12:13
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
One persons definition of "absolutely necessary" may not be the same as 
another's.  I
think flexibility should trump defensive programming of this sort.  The fact 
that
this is already in a separate namespace ("Protected") is perhaps enough 
information
so the user knows that it is not the default, recommended usage.
```

Original comment by `jeffdool...@gmail.com` on 10 Apr 2009 at 5:33

**Comment by GoogleCodeExporter** [comment]
```
Maybe you could elaborate on the intended usage anyways?

Thanks!
```

Original comment by `kzu.net` on 12 Apr 2009 at 3:53

**Comment by GoogleCodeExporter** [comment]
```
I have an interface with multiple string properties.  I have a class with a 
method
that calls properties on that interface.  I want to ensure that if new 
properties are
ever added to that interface, that the class method calls *all* properties on 
that
interface.  If a new property is added to the interface and the class does not 
call
all properties on the interface, then I want a unit test to fail.

In order to do this, I use reflection to determine what the properties are on 
the
interface.  Then in my test, I pass in a mock of the interface to the class 
method. 
I want to set expectations that all properties on the interface get called by 
the
class method.

If Moq let me use the "Protected" namespace to set my expectations, then I could
accomplish my goal.
```

Original comment by `jeffdool...@gmail.com` on 14 Apr 2009 at 7:41

**Comment by GoogleCodeExporter** [comment]
```
Yup, maybe "Unsafe" would be the proper naming for what you're trying to do.
In any case, you don't need to resort to that, you can still invoke the typed 
API via
reflection. Have you tried that way? I know it can be quite convoluted...
```

Original comment by `kzu.net` on 15 Apr 2009 at 11:26
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi, if you would allow to mock public methods, this would be a workaround for 
Issue
100:

interface ITest
{
   event EventHandler Load;
}

Mock<ITest> mock = new Mock<ITest>();
mock.Protected().Setup("add_Load", ItExpr.IsAny<EventHandler>());
mock.Object.Load += new EventHandler(MyTarget);
mock.VerifyAll();

Basically I agree that this limitation is right, but there should be a way to 
change
this behaviour. Maybe an overload of Mock.Protected() would be a good solution:

Mock.Protected(bool allowPublicMembers)

What do you think?

```

Original comment by `goo...@wimps.ch` on 20 Apr 2009 at 11:24

**Comment by GoogleCodeExporter** [comment]
```
I think the idea of an overload like allowPublicMembers would be a fine 
solution to
my issue as well.
```

Original comment by `jeffdool...@gmail.com` on 20 Apr 2009 at 2:50

**Comment by GoogleCodeExporter** [comment]
```
By design.
You can do this dinamically building the Expression Tree corresponding to your 
property and passing this expression tree to setup or verify.
```

Original comment by `marian...@gmail.com` on 31 May 2010 at 1:14
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Maybe we should rename the namespace import to "Unsafe" and allow you to do 
whatever 
you want.

Thoughts?
```

Original comment by `kzu.net` on 31 May 2010 at 2:58
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 11 Aug 2010 at 4:45
- Added labels: **Milestone-Release4.0**
