### ISSUE TITLE
NullReferenceException with simple mock

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#165]
```
What steps will reproduce the problem?
Run this code:
var mockEntityPropertyFactory = new Mock<IEntityPropertyFactory>();
            mockEntityPropertyFactory.Setup(factory => 
factory.Create(It.IsAny<IBentekEntity>(), It.IsAny<string>()))
                .Returns(new EntityProperty(null,null));

What is the expected output? What do you see instead?
I expect it not to crash on the second line. What I see is a 
NullReferenceException:
at Moq.MethodCall.SetFileInfo()
at Moq.MethodCall..ctor(Mock mock, Expression originalExpression, 
MethodInfo method, Expression[] arguments)
at Moq.MethodCallReturn`2..ctor(Mock mock, Expression originalExpression, 
MethodInfo method, Expression[] arguments)
at Moq.Mock.<>c__DisplayClass12`2.<Setup>b__11()
at Moq.PexProtector.Invoke<T>(Func`1 function)
at Moq.Mock.Setup<T1,TResult>(Mock mock, Expression`1 expression)
at Moq.Mock`1.Setup<TResult>(Expression`1 expression)
at EntityValidatorBaseTests.ValidateSet() in Class1.cs: line 32

What version of the product are you using? On what operating system?
Moq version: 3.1.416.3 
.Net version: 3.5SP1
OS: XP SP3

Please provide any additional information below.
This seems like a very basic mock to me...I saw on the Google Groups that 
this was a problem a while back with 3.0.
```

Original issue reported on code.google.com by `MikeTGa...@gmail.com` on 17 Apr 2009 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
r u running the test in release mode?
do any of the interfaces you're mocking live in a release-mode assembly with no 
debug
symbols?

Basically we're trying to be as helpful as possible in our error messages, and 
that
includes trying to see where exactly your calling code is (file/line), and for 
that
we try to reach the debug information in the stacktrace. 

But for some reason I can't seem to be able to reproduce this issue (which has 
been
reported twice now :( )
```

Original comment by `kzu.net` on 17 Apr 2009 at 7:11

**Comment by GoogleCodeExporter** [comment]
```
Everything is in Debug mode and the test project (a C# project) is linked to my 
interfaces through a project reference. My interfaces live in a VB.NET project 
if 
that helps.
```

Original comment by `MikeTGa...@gmail.com` on 17 Apr 2009 at 8:27

**Comment by GoogleCodeExporter** [comment]
```
Hi All,
I tried MOQ and even I am getting this error. Please note that I am using Visual
Studio 2008 and .NET 3.5. I dowloaded latest Moq 3.1. 

Regards,
Madhan
```

Original comment by `madhanga...@gmail.com` on 5 Jul 2009 at 6:00

**Comment by GoogleCodeExporter** [comment]
```
I never resolved this and had to roll back to using Moq 2.0 which works fine 
with my 
code.
```

Original comment by `MikeTGa...@gmail.com` on 6 Jul 2009 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
Did you try getting from our trunk and building a newer version?

IIRC, this was fixed in the trunk...
```

Original comment by `kzu.net` on 6 Jul 2009 at 2:17
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Seems to be the same as #181
```

Original comment by `marian...@gmail.com` on 6 Jul 2009 at 4:12
- Changed state: **Duplicate**
