### ISSUE TITLE
Interface that include IEnumerable will cause NullReferenceException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#174]
```
What steps will reproduce the problem?

1. Create interface that include IEnumerable, like this:

    public interface IServiceNo1 : IEnumerable{}

2. Create an interface that uses it:

    public interface ISomeCollaborator
    {
        void Collaborate(IServiceNo1 serviceNo1);
    }

3. Create and run a unit test that should pass:

   // Arrange
   var serviceNo1Mock = new Mock<IServiceNo1>();
   var collaboratorMock = new Mock<ISomeCollaborator>();

   // Act
   collaboratorMock.Object.Collaborate(serviceNo1Mock.Object);

   // Assert
   collaboratorMock.Verify(o => o.Collaborate(serviceNo1Mock.Object));


What is the expected output? What do you see instead?

  Instead of passing, you'll get the following exception:

System.NullReferenceException: Object reference not set to an instance of
an object.
   at Moq.ConstantMatcher.MatchesEnumerable(Object value)
   at Moq.ConstantMatcher.Matches(Object value)
   at Moq.MethodCall.Matches(IInvocation call)
   at Moq.Mock.<>c__DisplayClassc.<VerifyCalls>b__b(IInvocation i)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Moq.Mock.VerifyCalls(Interceptor targetInterceptor, MethodCall
expected, Expression expression, Times times)
   at Moq.Mock.Verify[T](Mock mock, Expression`1 expression, Times times,
String failMessage)
   at Moq.Mock`1.Verify(Expression`1 expression, String failMessage)
   at OriginalMoq.UnitTest1.Test_GetEnumerator_Bug() in
C:\MSVS2007_Development\Src\Test\UnitTesting\OriginalMoq\OriginalMoq\UnitTest1.c
s:line
93


What version of the product are you using? On what operating system?

   Moq version 3.1.416.3
   Win xp sp 3

WORKAROUND:

Just setup the "GetEnumerator" to return something, like this:

    serviceNo1Mock.Setup(o => o.GetEnumerator())
        .Returns(new object[0].GetEnumerator());


```

Original issue reported on code.google.com by `ittay.op...@gmail.com` on 8 Jun 2009 at 8:51

**Comment by GoogleCodeExporter** [comment]
```
we'll investigate.
```

Original comment by `kzu.net` on 9 Jun 2009 at 2:54
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Revision #583
```

Original comment by `marian...@gmail.com` on 9 Jun 2009 at 4:51
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Another workaround (of course) is:

collaboratorMock.Verify(o => o.Collaborate(It.Is<IServiceNo1>(srv => srv ==
serviceNo1Mock.Object)));

```

Original comment by `ittay.op...@gmail.com` on 10 Jun 2009 at 10:14

**Comment by GoogleCodeExporter** [comment]
```
hi 
For all database nulllable columns, we should either add null check or Do 
simple comparision ( a == b) ( instead of a.ToLower() == b.ToLower()) or 
similar string operations.
My observation as below:
As they get iterated through Enumerable of LINQ Query for comparision against 
with input string/value, any null value (of database column) and operations on 
it would raise exception, but Enumerable becomes NULL, though query is not null.


```

Original comment by `Phani.Ka...@gmail.com` on 28 Mar 2011 at 7:10
