### ISSUE TITLE
theMock.Object failing on VS2010 Beta 1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#175]
```
What steps will reproduce the problem?
1. Create unit test class
2. Create field variables being empty mock objects. In my case I have five 
of them:
private Mock<IFormsAuthentication> _formsAuthentication = new 
Mock<IFormsAuthentication>(MockBehaviour.Strict);
[...]
3. Each unit test then needs those five mocks to be passed in the 
constructor of the class being tested (in this case an ASP.NET MVC 
controller). The setup of each mock is done in each test.

What is the expected output? What do you see instead?
The expected output would be that all tests passed (just as they did in 
.NET 3.5 SP1 VS2008). Instead some tests fail with the exception: 
InvalidComObjectException: COM object that has been separated from its 
underlying RCW cannot be used.
If the tests are run individually they all pass.

What version of the product are you using? On what operating system?
Using Moq 3.1.0.0 on Windows 7 RC, Visual Studio 2010 Beta 1 and .NET 4 
Beta 1 (the project targets .NET 4 Beta 1 too).

Please provide any additional information below.
The stacktrace for the exception is:
   at System.StubHelpers.StubHelpers.StubRegisterRCW(Object pThis, IntPtr 
pThread)
   at 
Microsoft.Runtime.Hosting.IClrStrongName.StrongNameGetPublicKey(String 
pwzKeyContainer, Byte[] pbKeyBlob, Int32 cbKeyBlob, IntPtr& 
ppbPublicKeyBlob, Int32& pcbPublicKeyBlob)
   at 
Microsoft.Runtime.Hosting.StrongNameHelpers.StrongNameGetPublicKey(String 
pwzKeyContainer, Byte[] bKeyBlob, Int32 cbKeyBlob, IntPtr& 
ppbPublicKeyBlob, Int32& pcbPublicKeyBlob)
   at System.Reflection.StrongNameKeyPair.ComputePublicKey()
   at System.Reflection.StrongNameKeyPair.get_PublicKey()
   at System.Reflection.Emit.AssemblyBuilder..ctor(AppDomain domain, 
AssemblyName name, AssemblyBuilderAccess access, String dir, Evidence 
evidence, PermissionSet requiredPermissions, PermissionSet 
optionalPermissions, PermissionSet refusedPermissions, StackCrawlMark& 
stackMark, IEnumerable`1 unsafeAssemblyAttributes)
   at 
System.Reflection.Emit.AssemblyBuilder.InternalDefineDynamicAssembly(Assemb
lyName name, AssemblyBuilderAccess access, String dir, Evidence evidence, 
PermissionSet requiredPermissions, PermissionSet optionalPermissions, 
PermissionSet refusedPermissions, StackCrawlMark& stackMark, IEnumerable`1 
unsafeAssemblyAttributes)
   at System.AppDomain.InternalDefineDynamicAssembly(AssemblyName name, 
AssemblyBuilderAccess access, String dir, Evidence evidence, PermissionSet 
requiredPermissions, PermissionSet optionalPermissions, PermissionSet 
refusedPermissions, StackCrawlMark& stackMark, IEnumerable`1 
assemblyAttributes)
   at System.AppDomain.DefineDynamicAssembly(AssemblyName name, 
AssemblyBuilderAccess access)
   at Castle.DynamicProxy.ModuleScope.CreateModule(Boolean signStrongName)
   at Castle.DynamicProxy.ModuleScope.ObtainDynamicModuleWithStrongName()
   at Castle.DynamicProxy.ModuleScope.ObtainDynamicModule(Boolean 
isStrongNamed)
   at 
Castle.DynamicProxy.Generators.Emitters.ClassEmitter.CreateTypeBuilder(Modu
leScope modulescope, String name, Type baseType, Type[] interfaces, 
TypeAttributes flags, Boolean forceUnsigned)
   at 
Castle.DynamicProxy.Generators.Emitters.ClassEmitter..ctor(ModuleScope 
modulescope, String name, Type baseType, Type[] interfaces, TypeAttributes 
flags, Boolean forceUnsigned)
   at 
Castle.DynamicProxy.Generators.Emitters.ClassEmitter..ctor(ModuleScope 
modulescope, String name, Type baseType, Type[] interfaces, TypeAttributes 
flags)
   at 
Castle.DynamicProxy.Generators.Emitters.ClassEmitter..ctor(ModuleScope 
modulescope, String name, Type baseType, Type[] interfaces)
   at 
Castle.DynamicProxy.Generators.BaseProxyGenerator.BuildClassEmitter(String 
typeName, Type parentType, Type[] interfaces)
   at 
Castle.DynamicProxy.Generators.BaseProxyGenerator.BuildClassEmitter(String 
typeName, Type parentType, IList interfaceList)
   at 
Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCo
de(Type proxyTargetType, Type[] interfaces, ProxyGenerationOptions options)
   at 
Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarg
et(Type interfaceToProxy, Type[] additionalInterfacesToProxy, 
ProxyGenerationOptions options)
   at 
Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyTypeWithoutTarget(Ty
pe interfaceToProxy, Type[] additionalInterfacesToProxy, 
ProxyGenerationOptions options)
   at 
Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type 
interfaceToProxy, Type[] additionalInterfacesToProxy, 
ProxyGenerationOptions options, IInterceptor[] interceptors)
   at 
Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type 
interfaceToProxy, Type[] additionalInterfacesToProxy, IInterceptor[] 
interceptors)
   at Moq.Mock`1.<InitializeInstance>b__0()
   at Moq.PexProtector.Invoke(Action action)
   at Moq.Mock`1.InitializeInstance()
   at Moq.Mock`1.get_Object()
   at xyz.Test.AccountControllerTest.LogOnPostTestNotAllDataSpecified() in 
C:\xyz.Test\AccountControllerTest.cs:line 229

Putting the mock initializations under a method marked with 
[TestInitialize] results in the same errors.
```

Original issue reported on code.google.com by `martinla...@gmail.com` on 11 Jun 2009 at 8:24

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 11 Jun 2009 at 4:11
- Changed state: **Accepted**
- Added labels: **Milestone-Release3.5**, **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Can you please attach a clean repro?
```

Original comment by `kzu.net` on 16 Jun 2009 at 6:14

**Comment by GoogleCodeExporter** [comment]
```
I encountered this today as well. In my case, the error only happened if in one 
test
I used either the autogenerated Visual Studio private accessor, or manually 
called
PrivateObject.Invoke in a one test - then the Moq code generates the
InvalidComObjectException in the test that follows.  In both cases, commenting 
out
the access to the protected method stopped the exception from being thrown in 
the
subsequent test.

Here is the simplest reproduction I was able to get, a .net mvc project 
containing
only the error causing methods, built with VS 2010 beta1 / .net 4.0
```

Original comment by `chip.p...@gmail.com` on 23 Jun 2009 at 7:07

Attachments:
- [InvalidComObjectExceptionDemo.zip](https://storage.googleapis.com/google-code-attachments/moq/issue-175/comment-3/InvalidComObjectExceptionDemo.zip)

**Comment by GoogleCodeExporter** [comment]
```
We've found a workaround, which is to compile Moq without ILMerge (that is, with
separate Castle assemblies).
```

Original comment by `kzu.net` on 28 Jun 2009 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
And you need build against the trunk.
```

Original comment by `andrew.j...@gmail.com` on 16 Jul 2009 at 6:42

**Comment by GoogleCodeExporter** [comment]
```
Now we have a public drop.
Get the one that says "with Castle Assemblies".
```

Original comment by `kzu.net` on 17 Jul 2009 at 5:05

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 25 Oct 2009 at 4:09
- Added labels: **Milestone-Release4.0**
- Removed labels: **Milestone-Release3.5**

**Comment by GoogleCodeExporter** [comment]
```
Replacement of ILMerge fixed this issue.
```

Original comment by `marian...@gmail.com` on 3 Dec 2009 at 2:44
- Changed state: **Fixed**
