### ISSUE TITLE
How do I fix this error?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#180]
```
Hi

I want to test my part of code that returns the users password question. So
I have made a mockup of the Membership provider using MOQ.

I don't think I need to show you the actual code just the test part of it.

    // Arrange
               var membershipMock = new Mock<MembershipProvider>();

               membershipMock.Setup(m => m.GetUser("test",
false).PasswordQuestion).Returns("Password");


               authentication.Authenticate.Provider = membershipMock.Object;

               // Act

               var actual =
authentication.PasswordRecoveryStep1(It.IsAny<string>());

               // Assert

               Assert.That(actual, Is.EqualTo("Password"));



So when I run this in Nunit I get this:


Test.Controllers.AuthenticationControllerTest.Test_If_Password_Recovery_Setp1_Re
turns_Users_PasswordQuestion:
    System.NotSupportedException : Only property accesses are supported in
intermediate invocations on a setup. Unsupported expression
m.GetUser("test", False).

    at
Moq.Mock.AutoMockPropertiesVisitor.VisitMethodCall(MethodCallExpression m)
    at Moq.ExpressionVisitor.Visit(Expression exp)
    at Moq.Mock.AutoMockPropertiesVisitor.VisitMemberAccess(MemberExpression m)
    at Moq.ExpressionVisitor.Visit(Expression exp)
    at Moq.Mock.AutoMockPropertiesVisitor.SetupMocks(Expression expression)
    at Moq.Mock.GetInterceptor(LambdaExpression lambda, Mock mock)
    at Moq.Mock.<>c__DisplayClass15`2.<SetupGet>b__14()
    at Moq.PexProtector.Invoke[T](Func`1 function)
    at Moq.Mock.SetupGet[T1,TProperty](Mock mock, Expression`1 expression)
    at Moq.Mock.<>c__DisplayClass12`2.<Setup>b__11()
    at Moq.PexProtector.Invoke[T](Func`1 function)
    at Moq.Mock.Setup[T1,TResult](Mock mock, Expression`1 expression)
    at Moq.Mock`1.Setup[TResult](Expression`1 expression)
    at
Test.Controllers.AuthenticationControllerTest.Test_If_Password_Recovery_Setp1_Re
turns_Users_PasswordQuestion()
in D:\MvcApplication9\Test\Controllers\AuthenticationControllerTest.cs:line 186


So I am guessing it is something because of the property that I am trying
to access. I am not sure how to set it up. I am not very good with
lamdas(and have not been able to find a tutorial on them yet) so I am not
sure if I could some how arrange it differently to make it work.

Or if I just totally missed the mark.

Thanks

P.S I was not sure if this was the place to ask. If not please point me to
the support forum. If you don't have one why not?
```

Original issue reported on code.google.com by `mhub...@gmail.com` on 27 Jun 2009 at 12:01

**Comment by GoogleCodeExporter** [comment]
```
You have to mock the method invocation first, and the property access 
separately:

membershipMock.Setup(m => m.GetUser("test", false)).Returns(aUser);

// aUser would either be a mock itself, or it would have a hardcoded password.

The right place to ask question rather than report bugs is to email the 
discussion
group at http://groups.google.com/group/moqdisc
```

Original comment by `kzu.net` on 27 Jun 2009 at 3:46
- Changed state: **WontFix**
