### ISSUE TITLE
 Types extending from COM objects should override all methods of an interface implemented by the base COM class

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#213]
```
I try to mock a descendant of a COM Wrapper class.
I have overriden just a couple of methods that are implied in the test.
Moq complains when calling the mock that I did not override ALL methods.
Why should I do that?

Test method DiasTests.DialUpPerformanceCounterTests.TestMoq threw
exception:  System.ArgumentException: Type to mock must be an interface or
an abstract or non-sealed class.  --->  System.TypeLoadException: Types
extending from COM objects should override all methods of an interface
implemented by the base COM class..
at System.Reflection.Emit.TypeBuilder._TermCreateClass(Int32 handle, Module
module)
at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
at System.Reflection.Emit.TypeBuilder.CreateType()
at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType()
at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[]
interfaces, ProxyGenerationOptions options)
at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxy(Type
classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions
options)
at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy,
Type[] additionalInterfacesToProxy, ProxyGenerationOptions options,
Object[] constructorArguments, IInterceptor[] interceptors)
at Moq.Mock`1.<InitializeInstance>b__0()
--- End of inner exception stack trace ---
at Moq.Mock`1.<InitializeInstance>b__0()
at Moq.PexProtector.Invoke(Action action)
at Moq.Mock`1.InitializeInstance()
at Moq.Mock`1.get_Object()

```

Original issue reported on code.google.com by `livi...@gmail.com` on 7 Oct 2009 at 12:15
- Merged into: #254

**Comment by GoogleCodeExporter** [comment]
```
Doesn't look like a Moq issue, but even a Reflection.Emit (or at least 
DynamicProxy). 

We'll investigate if there's something we can do.

One question through, can't you mock the interface implemented by the wrapper 
instead?
```

Original comment by `kzu.net` on 7 Oct 2009 at 3:14

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 25 Oct 2009 at 4:20
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
AS part of Issue 254, we've verified that we can mock COM interfaces normally.
Feel free to reopen if you still face this issue with the latest v4 beta bits.

Thanks!
```

Original comment by `kzu.net` on 11 Aug 2010 at 5:07
- Changed state: **Duplicate**
