### ISSUE TITLE
DataConnection.State with MockBehavior.Strict

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#214]
```
What steps will reproduce the problem?
NUnit 2.5 with Moq 3.1.416.3  Cycle it 5 times
// ***** Start Code  *************
using System.Data.Common;
[Test]
public void RequiredOpen_Connection_True_Raw_Test()
{
  #region Arrange
  Mock<DbConnection> mockDataConnection = new
Moq.Mock<DbConnection>(MockBehavior.Strict);
  mockDataConnection.Setup(dc =>
dc.State).Returns(System.Data.ConnectionState.Open);
  #endregion
  #region Act
  Assert.AreEqual(System.Data.ConnectionState.Open,
mockDataConnection.Object.State);
  #endregion
  #region Assert
  #endregion
}
// ***** End Code  *************

What is the expected output? What do you see instead?
Should not throw an error.
Get on deallocation:
//***** Start Error Message  
Siemens.Library.Tests.Common_Contracts_Test.RequiredOpen_Connection_True_Raw_Tes
t:
An unhandled System.Runtime.Serialization.SerializationException was thrown
while executing this test : Unable to find assembly 'Moq,
Version=3.1.416.3, Culture=neutral, PublicKeyToken=69f491c39445e920'.
// ****** End Error Message
// ****** Start Stack
at
System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
at
System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemb
lyInfo
assemblyInfo, String name)
at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String
objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA,
Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader
objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray
assemIdToAssemblyTable)
at System.Runtime.Serialization.Formatters.Binary.ObjectMap.Create(String
name, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[]
typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32
objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
at
System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapT
yped(BinaryObjectWithMapTyped
record)
at
System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapT
yped(BinaryHeaderEnum
binaryHeaderEnum)
at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
at
System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHa
ndler
handler, __BinaryParser serParser, Boolean fCheck, Boolean
isCrossAppDomain, IMethodCallMessage methodCallMessage)
at
System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Strea
m
serializationStream, HeaderHandler handler, Boolean fCheck, Boolean
isCrossAppDomain, IMethodCallMessage methodCallMessage)
at
System.Runtime.Remoting.Channels.CrossAppDomainSerializer.DeserializeObject(Memo
ryStream
stm)
at System.AppDomain.Deserialize(Byte[] blob)
at System.AppDomain.UnmarshalObject(Byte[] blob)
//******** End Stack

What version of the product are you using? On what operating system?
XP 

Please provide any additional information below.
Does not product exception if MockBehavior.Loose.
```

Original issue reported on code.google.com by `complexi...@gmail.com` on 7 Oct 2009 at 4:25

**Comment by GoogleCodeExporter** [comment]
```
Why is there a cross-appdomain call at all? :|
```

Original comment by `kzu.net` on 25 Oct 2009 at 4:22
- Changed state: **Accepted**
- Added labels: **Milestone-Release4.0**

**Comment by GoogleCodeExporter** [comment]
```
Tested on rev #720
```

Original comment by `marian...@gmail.com` on 2 Jul 2010 at 10:09
- Changed state: **Invalid**
