### ISSUE TITLE
Moq does't work in console mode without debugging

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#215]
```
What steps will reproduce the problem?
1. Create a console program
2. Try to run without debugging
3. it crash

But if you run using debugger it works! 

error messsage:

Unhandled Exception: System.NullReferenceException: Object reference not 
set to
an instance of an object.
   at Moq.MethodCall.SetFileInfo()
   at Moq.MethodCall..ctor(Mock mock, Expression originalExpression, 
MethodInfo
method, Expression[] arguments)
   at Moq.MethodCallReturn`2..ctor(Mock mock, Expression 
originalExpression, Met
hodInfo method, Expression[] arguments)
   at Moq.Mock.<>c__DisplayClass12`2.<Setup>b__11()
   at Moq.PexProtector.Invoke[T](Func`1 function)
   at Moq.Mock.Setup[T1,TResult](Mock mock, Expression`1 expression)
   at Moq.Mock`1.Setup[TResult](Expression`1 expression)
   at MoqTest.Program.Main(String[] args) in C:\USERS\Visual Studio 
2008\Project
s\MoqTest\MoqTest\Program.cs:line 39
```

Original issue reported on code.google.com by `cristiano.francis` on 7 Oct 2009 at 7:54

**Comment by GoogleCodeExporter** [comment]
```
This shouldn't be hapenning as we fixed this a while ago.
Which version of Moq are you using?
```

Original comment by `kzu.net` on 25 Oct 2009 at 4:23

**Comment by GoogleCodeExporter** [comment]
```
This is failing for me with version 2.4.8 in the same way, works in the 
debugger and fails if just run as a console



using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Moq;
using System.Threading;

namespace MoqTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var mock = new Mock<IFoo>();
            //mock.Setup(m => m.Bar(It.IsAny<List<string>>())).Returns((List<string> list) => { return list.Count; });
            mock.Setup(m => m.Bar(null)).Returns(3);

            Thread.Sleep(2000);
            var onetwo = new List<string> { "one", "two" };
            var count = mock.Object.Bar(null);
            Console.WriteLine(count);
        }
    }

    public interface IFoo
    {
        int Bar(List<string> list);
    }
}

```

Original comment by `Rich.Kea...@gmail.com` on 23 Jun 2010 at 9:15

**Comment by GoogleCodeExporter** [comment]
```
Fixed on version 3
```

Original comment by `marian...@gmail.com` on 27 Jun 2010 at 4:37
- Changed state: **Invalid**
