### ISSUE TITLE
Index out of range exception thrown

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#225]
```
What steps will reproduce the problem?
1.  using TD.NET, right click in Test.Run and run the test
2.
3.

What is the expected output? What do you see instead?
nothing

What version of the product are you using? On what operating system?
latest, 4.0.??.  Win7x64

Please provide any additional information below.
Here's the code:

public interface IFoo
        {
            DateTime Bar { get; set; }
            decimal Bar1 { get; set; }
            decimal Bar3 { get; set; }
         #region Properties
        decimal Ask { get; }
        long AskSize { get; }
        decimal Bid { get; }
        long BidSize { get; }
        bool CanBuy { get; }
        decimal Change { get; }
        DateTime Date { get; }
        decimal DayChangePercentage { get; }
        //IDictionary<int, EmaCalculator> EmaCalculators { get; }
        //MacdCalculator MacdCalculator { get; }
        string Message { get; }
        decimal OpenPrice { get; }
        //public virtual long Id { get; set; }
        decimal Price { get; set; }
        //AssetQuoteTrend Trend { get; }
        //TrendDirection TrendDirection { get;  }
        TimeSpan TrendLength { get;  }
        IDictionary<int, Foo2> Trends { get; }
        //AssetQuoteType Type { get; }
        long Volume { get; }
        //AssetQuoteTrend Wave { get; }
        #endregion

        #region Methods
        void AddMessage(string message);
        //string Symbol { get; }
        void CalculateTrend(IFoo previousQuote);
        #endregion   
   }
   public class Foo2
   {
       //   public virtual AssetQuoteTrendType Type { get; set; }

       #region Properties
       public virtual decimal Change { get; set; }
       public virtual DateTime? Date { get; set; }
      // public virtual TrendDirection Direction { get; set; }
       #endregion

       #region Methods
       public override int GetHashCode()
       {
           return ToString().GetHashCode();
       }

       public override string ToString()
       {
           return Date + "," + "," + Change;
       }
       #endregion
   }
  public static class IFooExtensions
    {
        public static Mock<IFoo> Setup(this Mock<IFoo> item, int id)
        {
            item.SetupAllProperties();
            item.SetupGet(x => x.Bar).Returns(new DateTime(2009, id, id));
            item.SetupGet(x => x.Bar1).Returns(id);
            item.SetupGet(x => x.Bar3).Returns(id*.1m);
            return item;
        }
    }

  [TestFixture]

    public 
      class
      Test
  {


      public static readonly IFoo _foo;
      static Test()
      {
          //for (var i = 0; i < 6; i++)
          {
              _foo = new Mock<IFoo>() { DefaultValue = DefaultValue.Mock
}.Setup(1).Object;

          }
      }
      [Test]
      public void Run()
      {

      }
  }

and here's the stack:

TestFixture failed: System.TypeInitializationException : The type
initializer for 'StockTracker.Domain.Tests.Test' threw an exception.
  ----> System.Reflection.TargetInvocationException : Exception has been
thrown by the target of an invocation.
  ----> System.IndexOutOfRangeException : Index was outside the bounds of
the array.
   at
System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(IntPtr
type)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Core.Reflect.Construct(Type type)
   at NUnit.Core.TestSuite.CreateUserFixture()
   at NUnit.Core.TestSuite.DoOneTimeSetUp(TestResult suiteResult)
--TargetInvocationException
   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[]
arguments, SignatureStruct& sig, MethodAttributes methodAttributes,
RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture,
Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Moq.Mock.<>c__DisplayClass26.<SetupAllProperties>b__23()
   at Moq.Mock.SetupAllProperties(Mock mock)
   at Moq.Mock.<>c__DisplayClass26.<SetupAllProperties>b__23()
   at Moq.Mock.SetupAllProperties(Mock mock)
   at Moq.Mock`1.SetupAllProperties()
   at StockTracker.Domain.Tests.IFooExtensions.Setup(Mock`1 item, Int32 id)
in C:\Users\Documents\Projects\S\Source\Domain.Tests\Tests.cs:line 122
   at StockTracker.Domain.Tests.Test..cctor() in
C:\Users\Documents\Projects\S\Source\Domain.Tests\Tests.cs:line 143
--IndexOutOfRangeException
   at Moq.MethodCall..ctor(Mock mock, Expression originalExpression,
MethodInfo method, Expression[] arguments)
   at Moq.MethodCallReturn`2..ctor(Mock mock, Expression
originalExpression, MethodInfo method, Expression[] arguments)
   at Moq.Mock.<>c__DisplayClass15`2.<SetupGet>b__14()
   at Moq.PexProtector.Invoke[T](Func`1 function)
   at Moq.Mock.SetupGet[T1,TProperty](Mock mock, Expression`1 expression)
   at Moq.Mock`1.SetupGet[TProperty](Expression`1 expression)

0 passed, 1 failed, 0 skipped, took 2.56 seconds (NUnit 2.5).




```

Original issue reported on code.google.com by `cliftonf...@gmail.com` on 22 Dec 2009 at 8:55
- Merged into: #205

**Comment by GoogleCodeExporter** [comment]
```
This could be a duplicate of http://code.google.com/p/moq/issues/detail?id=205 
but I 
don't see any indexers. 
```

Original comment by `david.black.co.at@gmail.com` on 11 Feb 2010 at 12:34
