### ISSUE TITLE
Lambda Expressions throw Not Supported Exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#42]
```
I have the following problem.  I think its because the IL actually created 
causes the lambda expressions to be different objects, this confuses the 
mock framework.  With Rhino Mocks, I need to use IgnoreArguments.  Would 
prefer not to have too...



Mock being: mock = new Mock<IRepository<Bug>>();
Find being:   T Find(Func<T, bool> match);

     [Test]
       public void GetBug_ValidID_AssignedToSa()
       {
           mock.Expect(r => r.Find(bug => bug.ID == 1)).Returns(b);

           Bug actualBug = _controller.GetBug(1);
           Assert.AreEqual("sa", actualBug.User.username);
       }

My test fails with this exception:

BugControllerTests_Moq.GetBug_ValidID_AssignedToSa :
FailedSystem.NotSupportedException: Expression bug => (bug.ID = 1) is
not supported.
at Moq.MatcherFactory.CreateMatcher(Expression expression)
at Moq.MethodCall.<.ctor>b__0(Expression expr)
at System.Linq.Enumerable.<SelectIterator>d__d`2.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray<TSource>(IEnumerable`1 source)
at Moq.MethodCall..ctor(Expression originalExpression, MethodInfo
method, Expression[] arguments)
at Moq.Mock`1.<Expect>b__4<TResult>(Expression original, MethodInfo
method, Expression[] args)
at Moq.Mock`1.ExpectImpl(Expression expression, Func`4 factory)
at Moq.Mock`1.Expect<TResult>(Expression`1 expression)
at
BusinessLayer.Tests.BugControllerTests_Moq.GetBug_ValidID_AssignedToSa()
in BugControllerTests_Moq.cs: line 74
```

Original issue reported on code.google.com by `ben200...@gmail.com` on 19 Apr 2008 at 11:00

**Comment by GoogleCodeExporter** [comment]
```
For now, you could use It.IsAny<Func<...>>()
```

Original comment by `kzu.net` on 23 Apr 2008 at 2:05

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 4 Jul 2008 at 5:11
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
We are not planning on supporting apis with delegates specified in the Expect, 
as
they will get converted by the compiler into expression trees, and there's no 
clear
way to compare (perform matching) delegates so as to know when the expectation 
was
satisfied.

It's suggested that you use IsAny<> together with a callback for this scenario.
```

Original comment by `kzu.net` on 4 Jul 2008 at 7:17
- Changed state: **WontFix**
