### ISSUE TITLE
Adding an EventHandler to a inherited event in an interface throws ArgumentNullException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#46]
```
What steps will reproduce the problem?
1. Compile and run the following code 
using System;
using Moq;

public interface IParent {
  event EventHandler<EventArgs> Event;
}

public interface IDerived : IParent { }

class Program {
  static void Main(string[] args) {
    var foo = new Mock<IParent>(MockBehavior.Strict);
    foo.Object.Event += (o, e) => { ;};  // this works

    var bar = new Mock<IDerived>(MockBehavior.Strict);
    bar.Object.Event += (o, e) => { ;}; // Exception Fired here
  }
}
What is the expected output? What do you see instead?
Expected: No exception

Actual:
System.ArgumentNullException was unhandled
  Message="Value cannot be null.\r\nParameter name: key"
  Source="mscorlib"
  ParamName="key"
  StackTrace:
       at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument 
argument)
       at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
       at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, 
TValue& value)
       at Moq.Mock.AddEventHandler(EventInfo ev, Delegate handler)
       at Moq.Interceptor.Intercept(IInvocation invocation)
       at Castle.DynamicProxy.AbstractInvocation.Proceed()
       at IDerivedProxy2341d997610044bebe345bf4a518d85f.add_Event
(EventHandler`1 value)
       at Program.Main(String[] args) in 
D:\Users\John\Documents\Code\ConsoleApplication1\ConsoleApplication1
\Program.cs:line 14
       at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] 
args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence 
assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext 
executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 


What version of the product are you using? On what operating system?
  CTP 2.5 from the main page -- version # 2.5.3029.17367
  Windows Vista Ultimate.  VS 2008 Professional

Please provide any additional information below.
  Interceptor.Intercept(IInvocation) calls GetEvent on the mock's type to 
try and get the EventInfo for the Event.  If the event is actually in an 
ancestor interface, this method fails and returns null.  When the mock 
tries to use the EventInfo as a dictionary key the dictionary throws 
ArgumentNullException
```

Original issue reported on code.google.com by `johnmelv...@gmail.com` on 2 May 2008 at 6:12

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 2 May 2008 at 6:23
- Added labels: **Milestone-Release2.5**, **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
The attached Diff file fixes this issue.  Unfortunatly I reflexively hit 
my "reformat" key in visual studio, so the diff has more junk than I would 
like.  
The actual changes are summarized below:

Design:
   The bug report makes the fix obvious: if the GetEvent fails, then we should find 
and search ancestor types and interfaces.  Beause the present object does not 
implement the method, there cannot be name collisions, so the order of the 
search is 
arbitrary.  A simple breadth first algorithm is used.  The first matching event 
is 
used and no attempt is made to reconcile multiple matches.  I believe that the 
final 
return null will never occurr, it would require the function to be called by a 
nonexistant event, which is precluded by the fact that this is intercepting a 
access 
already verified by the C# type system.

I had originally tried to muck with the BindingAttributes on the GetEvent call 
to 
include FlattenHierachy.  This attempt did not resolve this issue and caused 
several 
regressions, so it was abandoned.

Start by adding a test to expose the bug:
Index: UnitTests/Regressions/InheritedInterfaceEventError.cs
===================================================================
--- UnitTests/Regressions/InheritedInterfaceEventError.cs   (revision 0)
+++ UnitTests/Regressions/InheritedInterfaceEventError.cs   (revision 0)
@@ -0,0 +1,23 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using Xunit;
+using Moq;
+
+namespace Moq.Tests.Regressions {
+  public class InheritedInterfaceEventError {
+    public interface IParent {
+      event EventHandler<EventArgs> Event;
+    }
+
+    public interface IDerived : IParent { }
+
+    [Fact]
+    public void InheritedInterfaceTest() {
+      var bar = new Mock<IDerived>(MockBehavior.Strict);
+      bar.Object.Event += (o, e) => { ;}; // Exception Fired here
+    }
+
+  }
+}


In Interceptor.cs change the following line -- to invoke a custom search routine
- var eventInfo = targetType.GetEvent(invocation.Method.Name.Replace("add_", 
""));
+ EventInfo eventInfo = GetEventFromName(invocation.Method.Name.Replace("add_", 
""));

and add the following two methods which implement the bredth first search
+    /// <summary>
+    /// Get an eventInfo for a given event name.  Search type ancestors depth 
first 
if necessary.
+    /// </summary>
+    /// <param name="eventName">Name of the event, with the set_ or get_ 
prefix 
already removed</param>
+    private EventInfo GetEventFromName(string eventName) {
+      var depthFirstProgress = new Queue<Type>();
+      depthFirstProgress.Enqueue(targetType);
+      while (depthFirstProgress.Count > 0) {
+        var currentType = depthFirstProgress.Dequeue();
+        var eventInfo = currentType.GetEvent(eventName);
+        if (eventInfo != null)
+          return eventInfo;
+        //else
+        foreach (var implementedType in GetAncestorTypes(currentType)) {
+          depthFirstProgress.Enqueue(implementedType);
+        }
+      }
+      return null;
+    }
+
+    /// <summary>
+    /// Given a type return all of its ancestors, both types and interfaces.
+    /// </summary>
+    /// <param name="initialType">The type to find immediate ancestors 
of</param>
+    private IEnumerable<Type> GetAncestorTypes(Type initialType) {
+      Type baseType = initialType.BaseType;
+      if (baseType != null)
+        yield return baseType;
+      foreach (var implementedInterface in initialType.FindInterfaces(new 
TypeFilter
((foo, bar) => true), null)) {
+        yield return implementedInterface;
+      }
+    }
```

Original comment by `johnmelv...@gmail.com` on 5 May 2008 at 8:30

Attachments:
- [AncestorInterface.patch](https://storage.googleapis.com/google-code-attachments/moq/issue-46/comment-2/AncestorInterface.patch)

**Comment by GoogleCodeExporter** [comment]
```
Applied the patch. http://code.google.com/p/moq/source/detail?r=161

Thanks John!
```

Original comment by `kzu.net` on 25 May 2008 at 4:52
- Changed state: **Fixed**
