### ISSUE TITLE
Improve error message when callback has the wrong number of parameter types

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#54]
```
If the method to invoke receives (say) 2 args, but the Callback<T>() is
specified with a different number of args, a very ugly exception is thrown:

failed: System.Reflection.TargetParameterCountException : Parameter count
mismatch.
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags
invokeAttr, Binder binder, Object[] parameters, CultureInfo culture,
Boolean skipVisibilityChecks)
    at System.Delegate.DynamicInvokeImpl(Object[] args)
    at System.Delegate.DynamicInvoke(Object[] args)
    C:\Code\GoogleCode\GeoChat\trunk\Lib\Moq\Source\Extensions.cs(62,0): at
Moq.Extensions.InvokePreserveStack(Delegate del, Object[] args)


We should provide a better error message that helps diagnosing the problem.
```

Original issue reported on code.google.com by `kzu.net` on 12 May 2008 at 6:47

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 17 Nov 2008 at 12:57
- Changed state: **Fixed**
- Added labels: **Milestone-Release3.0**

**Comment by GoogleCodeExporter** [comment]
```
Hi guys,
I just ran into this issue and it took me ages to figure it out. It wasn't 
until I
came across this issue that i figured out what i had done wrong.
Thanks for fixing.
Anthony
```

Original comment by `vdh....@gmail.com` on 6 Jan 2009 at 6:20

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I can verify that this issue still isn't fixed. I'm seeing this issue in 3.1.
```

Original comment by `adrian.p...@gmail.com` on 28 Oct 2010 at 11:31
