### ISSUE TITLE
It is not possible to mock a generic interface with method constrained to interface argument

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#62]
```
*What steps will reproduce the problem?*
1. Create a following interface:
public interface ISomething<T> {
    void DoSomething<U>() where U : T;
}

2. Try to create a mock:
var mock = new Mock<ISomething<object>>();
// object is not important, any type causes same effect

*What is the expected output?*

Mock is created.

*What do you see instead?*

Method 'DoSomething' on type 
'ISomething`1Proxydfe5187d3b294661855d4251f1bbdcab' from assembly 
'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=null' tried to implicitly implement an interface method 
with weaker type parameter constraints.
    System.TypeLoadException
    Message: Method 'DoSomething' on type 
'ISomething`1Proxydfe5187d3b294661855d4251f1bbdcab' from assembly 
'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=null' tried to implicitly implement an interface method 
with weaker type parameter constraints.
    Source: mscorlib
    StackTrace:
    at System.Reflection.Emit.TypeBuilder._TermCreateClass(Int32 
handle, Module module)
    at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
    at System.Reflection.Emit.TypeBuilder.CreateType()
    at 
Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType()
    at 
Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCode(Ty
pe 
proxyTargetType, Type[] interfaces, ProxyGenerationOptions options)
    at 
Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarget(Ty
pe 
theInterface, Type[] interfaces, ProxyGenerationOptions options)
    at 
Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type 
theInterface, Type[] interfaces, ProxyGenerationOptions options, 
IInterceptor[] interceptors)
    at Moq.Mock`1..ctor(MockBehavior behavior, Object[] args)
    at Moq.Mock`1..ctor()

*What version of the product are you using? On what operating system?*

Moq 2.5.3029.17367 (2.5ctp)
```

Original issue reported on code.google.com by `ashm...@gmail.com` on 4 Jun 2008 at 1:54

**Comment by GoogleCodeExporter** [comment]
```
Looks like a Castle DynamicProxy issue.
Could you check at their forums too?
```

Original comment by `kzu.net` on 4 Jun 2008 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
What version of DP are you using?
From this: http://forum.castleproject.org/
viewtopic.php?p=9654&sid=66ae7d07b721b9c40527b83c9a8baef3 it seems that DP2 RC3 
should work fine.
```

Original comment by `ashm...@gmail.com` on 5 Jun 2008 at 9:04

**Comment by GoogleCodeExporter** [comment]
```
Excelent news!
Will integrate the new build ASAP.
We had to patch it 'cause of a problem creating proxies for WCF services...
```

Original comment by `kzu.net` on 5 Jun 2008 at 12:26

**Comment by GoogleCodeExporter** [comment]
```
Just added the regression test to our suite, but it doesn't pass with the 
latest DP2
binaries (file/product version 2.0.3.4333)

You should report this issue on their forum.
```

Original comment by `kzu.net` on 5 Jun 2008 at 3:43
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
For now it seems it is a framework bug with no workaround.
In Rhino Mocks the proposed solution is to use the CreateMockWithRemoting, 
which 
forces remoting proxy instead of dynamic assembly, so it works for interfaces 
and 
MarshalByRefs only, but at least works somehow.

You can track this thread http://groups.google.com/group/castle-project-users/
browse_thread/thread/a17066d7a503acd4# I just created, maybe we'll get some 
definite 
answer.

I wonder if it is possible to patch the DP2 dynamic assembly with Mono.Cecil, 
it may 
solve the issue, but is too complex to dig into it for now.
```

Original comment by `ashm...@gmail.com` on 5 Jun 2008 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
Am I correct that there is no special support for MarshalByRefObject in Moq 
since 
revision 145? If so, then the text on the home page got somewhat out of date.

Anyway, there are only two ways to fix the current issue:
1. Force such interface to be created with remoting (which seems too hard to do 
since there is no built-in remoting implementation).
2. Patch DynamicProxy2 to use Cecil, nice project to work on, but a bit out of 
topic 
for Moq.

So it seems this issue can be postponed until DP2 is fixed.
```

Original comment by `ashm...@gmail.com` on 8 Jun 2008 at 12:31

**Comment by GoogleCodeExporter** [comment]
```
It is correct that we dropped support for MBROs a while back (and that the 
homepage
is out of date hence :( ). Just fixed the homepage. 

We removed that as it wasn't clear what value it brought, it complicated the
implementation, made some behavior inconsistent with "pure" mocks (non-MBROs), 
and it
introduced one more concept/way to do things that we didn't want to expose in 
the API. 

I've heard about Cecil before... is that something you are familiar with?

BTW, unfortunately this bug seems to be one in the .NET classes 
(Reflection.Emit), so
this may not even be a matter of waiting for a DP2 fix :(. Looking at Cecil 
might be
something the Castle DP project could do also... 
```

Original comment by `kzu.net` on 9 Jun 2008 at 1:29

**Comment by GoogleCodeExporter** [comment]
```
I have used Cecil for IL analysis, but not for IL generation. This bug is 
definitely 
in Reflection.Emit. But AFAIK Cecil provides its own Emit facilities, and is 
also 
open source, so there are no unfixable bugs in it.

In a Google Groups thread referenced above, Ayende says that in general it 
would be 
a good idea for Castle people to try using Cecil instead of Reflection.Emit. Of 
course, this gives no dates of when that may be done.

I may try to implement that if they have great tests, but I do not think I will 
have 
time to do it in the near future.
```

Original comment by `ashm...@gmail.com` on 9 Jun 2008 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
Yup, would be good to have that implemented in DP2... 

It's a deep hackery pet project indeed... will put it in my backlog too :)
```

Original comment by `kzu.net` on 9 Jun 2008 at 12:42

**Comment by GoogleCodeExporter** [comment]
```
Postponed until a fix is available in DP2
```

Original comment by `kzu.net` on 9 Jun 2008 at 12:42
- Changed state: **WontFix**
