### ISSUE TITLE
System.InvalidCastException : Unable to cast object of type 'System.Reflection.Module' to type 'System.Reflection.Emit.ModuleBuilder'. 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#84]
```
Hi,

downloaded as version 2.5.2, dlls are marked with version 2.5.1.0
using nunit version 2.4.7.

  when I made some experimental tests, everything was just fine, unless 
they run in sequence in n-unit. When each of the tests is running 
separatelly, everything is OK, but when they are run in sequence, they 
fails on the exception:

----------------------------------------------------

System.InvalidCastException : Unable to cast object of 
type 'System.Reflection.Module' to 
type 'System.Reflection.Emit.ModuleBuilder'. 
 at System.Reflection.Emit.AssemblyBuilderData.GetInMemoryAssemblyModule()
at System.AppDomain.InternalDefineDynamicAssembly(AssemblyName name, 
AssemblyBuilderAccess access, String dir, Evidence evidence, PermissionSet 
requiredPermissions, PermissionSet optionalPermissions, PermissionSet 
refusedPermissions, StackCrawlMark& stackMark, IEnumerable`1 
unsafeAssemblyAttributes)
at System.AppDomain.DefineDynamicAssembly(AssemblyName name, 
AssemblyBuilderAccess access)
at Castle.DynamicProxy.ModuleScope.CreateModule(Boolean signStrongName)
at Castle.DynamicProxy.ModuleScope.ObtainDynamicModuleWithWeakName()
at Castle.DynamicProxy.ModuleScope.ObtainDynamicModule(Boolean 
isStrongNamed)
at Castle.DynamicProxy.Generators.Emitters.ClassEmitter.CreateTypeBuilder
(ModuleScope modulescope, String name, Type baseType, Type[] interfaces, 
TypeAttributes flags, Boolean forceUnsigned)
at Castle.DynamicProxy.Generators.Emitters.ClassEmitter..ctor(ModuleScope 
modulescope, String name, Type baseType, Type[] interfaces, TypeAttributes 
flags, Boolean forceUnsigned)
at Castle.DynamicProxy.Generators.Emitters.ClassEmitter..ctor(ModuleScope 
modulescope, String name, Type baseType, Type[] interfaces, TypeAttributes 
flags)
at Castle.DynamicProxy.Generators.Emitters.ClassEmitter..ctor(ModuleScope 
modulescope, String name, Type baseType, Type[] interfaces)
at Castle.DynamicProxy.Generators.BaseProxyGenerator.BuildClassEmitter
(String typeName, Type parentType, Type[] interfaces)
at Castle.DynamicProxy.Generators.BaseProxyGenerator.BuildClassEmitter
(String typeName, Type parentType, IList interfaceList)
at 
Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCo
de(Type proxyTargetType, Type[] interfaces, ProxyGenerationOptions options)
at 
Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarg
et(Type theInterface, Type[] interfaces, ProxyGenerationOptions options)
at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyTypeWithoutTarget
(Type theInterface, Type[] interfaces, ProxyGenerationOptions options)
at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget
(Type theInterface, Type[] interfaces, ProxyGenerationOptions options, 
IInterceptor[] interceptors)
at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget
(Type theInterface, Type[] interfaces, IInterceptor[] interceptors)
at Moq.Mock`1.InitializeInstance()
at Moq.Mock`1.get_Object()

----------------------------------------------------

I don't know what could be possibly wrong. I do not see any dependency 
between the test, except they try to mock the same iterface...

```

Original issue reported on code.google.com by `ge...@seznam.cz` on 25 Jul 2008 at 2:07

**Comment by GoogleCodeExporter** [comment]
```
Just checked the latest version (dll 2.6.0.0) and it behaves the same.
```

Original comment by `ge...@seznam.cz` on 25 Jul 2008 at 2:19

**Comment by GoogleCodeExporter** [comment]
```
Has been anything like this reported on Castle DP project?
```

Original comment by `kzu.net` on 31 Jul 2008 at 6:01

**Comment by GoogleCodeExporter** [comment]
```
Well, something similar is at 
http://forum.castleproject.org/viewtopic.php?t=4417

The installation is the same for me - net2.0sp1, net3.5 installed
```

Original comment by `ge...@seznam.cz` on 1 Aug 2008 at 7:18

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Took a look at this thread:
http://forum.castleproject.org/viewtopic.php?t=4417
The thread would seem to indicate that the Castle bug has been fixed, so...

Downloaded a recent Castle build (Build 923) from here: 
http://builds.castleproject.org/cruise/index.castle

Recompiled the latest trunk build of Moq with newer castle dlls (release build).

Still getting the same errors, but only when tests are run as a suite. A single 
test
run does not fail (as in the original reported problem).
```

Original comment by `davidrki...@gmail.com` on 11 Aug 2008 at 1:11

**Comment by GoogleCodeExporter** [comment]
```
Sorry to spam :-) but one more thing.

I do not get this error on a 64-bit machine (XP64) but my colleagues and our 
build
server (all 32-bit) exhibit this problem.
```

Original comment by `davidrki...@gmail.com` on 11 Aug 2008 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
This is very weird... I develop on an x64 Vista and never saw it either :S
```

Original comment by `kzu.net` on 11 Aug 2008 at 3:18

**Comment by GoogleCodeExporter** [comment]
```
Yep. Mine is all 32bit only.
```

Original comment by `ge...@seznam.cz` on 13 Aug 2008 at 11:28

**Comment by GoogleCodeExporter** [comment]
```
when upgraded to new version, it still looked buggy, but then we upgraded our 
buildserver from .net3.5 to .net3.5 sp1 and the problem seems to be fixed.
```

Original comment by `ge...@seznam.cz` on 9 Oct 2008 at 7:46

**Comment by GoogleCodeExporter** [comment]
```
fixed with NET sp1
```

Original comment by `kzu.net` on 9 Oct 2008 at 2:38
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 18 Jan 2009 at 11:57
- Added labels: **Milestone-Release2.5**
