### ISSUE TITLE
VerifyAll() throws an exception when Never() has been set

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ameniameni/moq#98]
```
Current code version r317 throws an exception on VerifyAll() when Never()
is set.

Looks like Moq.Interceptor.VerifyAll() is being called which results in
true being returned instead of false.

Code
====
interface ITest
{
   void DoNotCall();
}

Mock<ITest> mock = new Mock<ITest>();
mock.Expect(v=>v.DoNotCall()).Never();
mock.VerifyAll(); // should not throw an exception since the DoNotCall
method is never called

Exception details
=================
Moq.MockVerificationException : The following expectations were not met:
ITest v => v.DoNotCall()
 at Moq.Mock.VerifyAll(Interceptor interceptor)
 at Moq.Mock`1.VerifyAll()

```

Original issue reported on code.google.com by `mlyons.i...@gmail.com` on 6 Oct 2008 at 8:31

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 6 Oct 2008 at 2:42
- Changed state: **Started**
- Added labels: **Milestone-Release3.0**

**Comment by GoogleCodeExporter** [comment]
Original comment by `kzu.net` on 6 Oct 2008 at 2:43
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Brilliant, works perfect now thanks.
```

Original comment by `mlyons.i...@gmail.com` on 6 Oct 2008 at 11:56
